# Generated by Django 4.0.3 on 2022-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_userinfo_aadhar_alter_userinfo_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.CharField(max_length=100),
        ),
    ]
