# Generated by Django 3.2 on 2022-04-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_userinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.CharField(max_length=100, null=True)),
                ('vehicleNo', models.CharField(max_length=100, null=True)),
                ('modelName', models.CharField(max_length=12, null=True)),
                ('vehicleColor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='aadhar',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
