# Generated by Django 3.2 on 2022-04-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20220410_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='VehicleInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
